# delhi release

edgex-core-command:
  enabled: true
  image: edgexfoundry/docker-core-command-go:1.1.0
  command: ["/core-command", "-p", "docker"]
  init_wait: false

edgex-core-consul:
  enabled: true
  image: edgexfoundry/docker-edgex-consul:1.1.0
  command: ["/bin/sh", "-c", "docker-entrypoint.sh agent -dev -client 0.0.0.0"]

edgex-core-data:
  enabled: true
  image: edgexfoundry/docker-core-data-go:1.1.0
  command: ["/core-data", "-p", "docker"]

edgex-core-metadata:
  enabled: true
  image: edgexfoundry/docker-core-metadata-go:1.1.0
  command: ["/core-metadata","--profile=docker","--confdir=/res"]

edgex-device-virtual:
  enabled: true
  image: edgexfoundry/docker-device-virtual-go:1.1.1
  command: ["/bin/sh", "-c", "java -jar -Djava.security.egd=file:/dev/urandom -Xmx100M $APP_DIR/$APP"]

edgex-export-client:
  enabled: true
  image: edgexfoundry/docker-export-client-go:1.1.0
  command: ["/export-client","--profile=docker","--confdir=/res"]

edgex-export-distro:
  enabled: true
  image: edgexfoundry/docker-export-distro-go:1.1.0
  command: ["/bin/sh", "-c", "/export-distro"]

edgex-mongo:
  enabled: true
  image: edgexfoundry/docker-edgex-mongo:1.1.0

edgex-support-logging:
  enabled: true
  image: edgexfoundry/docker-support-logging-go:1.1.0
  command: ["/support-logging","--profile=docker","--confdir=/res"]

edgex-support-notifications:
  enabled: true
  image: edgexfoundry/docker-support-notifications-go:1.1.0
  command: ["/support-notifications","--profile=docker","--confdir=/res"]

edgex-support-rulesengine:
  enabled: true
  image: edgexfoundry/docker-support-rulesengine:1.1.0
  command: ["/bin/sh", "-c", "java -jar -Djava.security.egd=file:/dev/urandom -Xmx100M $APP"]

edgex-support-scheduler:
  enabled: true
  image: edgexfoundry/docker-support-scheduler-go:1.1.0
  command: ["/support-scheduler","--profile=docker"]

# Config seed will populate consul config
edgex-config-seed:
  enabled: true
  image: edgexfoundry/docker-core-config-seed-go:1.1.0
  init_wait: True
  command: ["/edgex/cmd/config-seed/config-seed","--profile=docker","--cmd=/edgex/cmd"]

edgex-ui-go:
  enabled: true
  image: edgexfoundry/docker-edgex-ui-go:1.1.0

# Black Box Testing

edgex-blackbox-testing:
  image: edgexfoundry/blackbox-testing:latest
  enabled: true

# API Security Gateway

edgex-kong:
  image: kong:1.3.0
  enabled: true

edgex-kong-db:
  enabled: true
  image: postgres:9.6

edgex-vault:
  enabled: true
  image: edgexfoundry/docker-edgex-secret-store-go:1.1.0
  workerImage: edgexfoundry/docker-edgex-security-secretstore-setup-go:1.1.0



